code/bacheca/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'bacheca'

urlpatterns = [  
    path('posts/', search_posts, name="posts"),
    path('annunci/', search_announcements, name="announcements"),

    path('post/<pk>/', DetailPostView.as_view(), name="post"),
    path('annuncio/<pk>/', DetailAnnouncementView.as_view(), name="announcement"),

    path('aggiungipost/', CreatePostView.as_view(), name="addpost"),
    path('aggiungiannuncio/', CreateAnnouncementView.as_view(), name="addannouncement"),

    path('authorizepost/', AuthorizePostView.as_view(), name="authorizepost"),
    path('approvepost/<pk>/', ApprovePostView.as_view(), name="approvepost"),

    path('commentapost/<int:id_post>/', CreateCommPostView.as_view(), name="addcommpost"),
    path('commentaannuncio/<int:id_ann>/', CreateCommAnnouncementView.as_view(), name="addcommannouncement"),

    path('eliminapost/<pk>/', DelPostView.as_view(), name="delpost"),
    path('eliminaannuncio/<pk>/', DelAnnouncementView.as_view(), name="delannouncement"),

    path('eliminacommentopost/<int:id_post>/<pk>/', DelCommPostView.as_view(), name="delcommpost"),
    path('eliminacommentoannuncio/<int:id_ann>/<pk>/', DelCommAnnouncementView.as_view(), name="delcommannouncement"),

    path('likepost/<int:id_post>/', like_post, name="likepost"),
    path('unlikepost/<int:id_post>/', unlike_post, name="unlikepost"),
]

code/societa/urls.py
from django.urls import path
from .views import *

app_name = 'societa'

urlpatterns = [  
    path('soci/', ListMemberView.as_view(), name="members"),
    path('sponsor/', ListSponsorView.as_view(), name="sponsors"),

    path('aggiungisocio/', CreateMemberView.as_view(), name="createmember"),
    path('aggiungisponsor/', CreateSponsorView.as_view(), name="createsponsor"),

    path('amministra/', adminClub, name="adminclub"),

    path('cancellasocio/<pk>/', DelMemberView.as_view(), name="delmember"),
    path('modificasocio/<pk>/', ModMemberView.as_view(), name="modmember"),

    path('cencellasponsor/<pk>/', DelSponsorView.as_view(), name="delsponsor"),
    path('modificasponsor/<pk>/', ModSponsorView.as_view(), name="modsponsor"),
]

code/sportnet/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r"^$|^/$|^home/$", home, name="home"),

    path('success/<str:back_url>', success_view, name="success"),

    path('register/', BasicUserCreateView.as_view(), name="register"),
    path('registersuper/',SuperUserCreateView.as_view(), name="registersuper"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('authorize/', AuthorizeUserView.as_view(), name="authorize"),
    path('approveuser/<pk>/', ApproveUserView.as_view(), name="approve"),

    path('squadre/', include('squadre.urls')),

    path('societa/', include('societa.urls')),

    path('bacheca/', include('bacheca.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

init_db()

code/squadre/urls.py
from django.urls import path
from .views import *


app_name = 'squadre'


urlpatterns = [
    path('', ListTeamsView.as_view(), name="teams"),
    path('rosa/<pk>/', DetailTeamView.as_view(), name="team"),

    path('giocatore/<pk>/', DetailPlayerView.as_view(), name="player"),

    path('partite/', search_games, name="games"),
    path('aggiungipartita/', CreateGameView.as_view(), name="creategame"),
    path('risultatopartita/<pk>/', ResGameView.as_view(), name="resgame"),
    path('convocazionepartita/<pk>/', ConGameView.as_view(), name="congame"),
    path('cancellapartita/<pk>/', DelGameView.as_view(), name="delgame"),
    
    path('squadrapreferita/<pk>/', SetPrefTeamView.as_view(), name="prefteam"),

    path('stampaconvocati/<int:id_game>/', print_convocation, name="printcov"),
    
]

code/templates/apprUsr.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>
{% if behavior != "error" %}
    <form method="post">{% csrf_token %}
        
        <p>Sicuro di voler approvare l'utente {{ object.username }}?</p>
        
        <input type="submit" value="Conferma">
        <!-- TODO aggiungere pulsante annulla -->
    </form>
{% else %}
    <h2>Errore</h2>
    <a href="{% url 'authorize' %}"><button type="button">Indietro</button></a>
{% endif %}

{% endblock content %}

code/templates/authUsrs.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<div>
    <table>
        <tr>
            <th>Utente</th>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Autorizza</th>
        </tr>

        {% for l in object_list|dictsort:"username" %}
        <tr>
            <th><p>{{l.username}}</p></th>
            <th><p>{{l.first_name}}</p></th>
            <th><p>{{l.last_name}}</p></th>
            <th><a href="{% url 'approve' l.pk %}"><button type="button">Autorizza</button></a></th>
        </tr>

        {% endfor %}
    </table>

</div>

{% endblock content %}

code/templates/base.html
<!DOCTYPE html>
<html lang="it">
<head>
    {% load static %}
    
    <meta charset="UTF-8">
    <link href="{% static 'css/styleSlider.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    {% block head %} {% endblock %}

    <title> {% block title %}{% endblock %}</title>
</head>
<body>
    {% include "navbar.html" %}
    <div>
    {% block content %}

    {% endblock %}
    </div>
    {% block js_files %}
    
    {% endblock %}
</body>
</html>

code/templates/delObj.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<br>

<form method="post">{% csrf_token %}
     
    <p>Sicuro di voler cancellare "{{ object }}"?</p>
     
    <input type="submit" value="Elimina">
    <!-- TODO aggiungere pulsante annulla -->
</form>   

{% endblock %}

code/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
{% for t in Team.objects.all %}
{{t}}
{% endfor%}
{% if user.is_authenticated %}
    <h1>Benvenuto {{user.username}}</h1>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
    {% include "slider.html" %}<br><br>
    <a href="{% url 'squadre:prefteam' user.pk %}">
        <button type="button">Scegli squadra da seguire</button> 
    </a>
    {% if user.follow.team != None and user.follow.team != "" %}
        <p>Attualmente stai seguendo {{user.follow.team}}</p>
        <a href="{% url 'squadre:games' %}">
            <h2>Calendario partite da disputare per {{user.follow.team}}</h2>
        </a>
    {% else %}
        <a href="{% url 'squadre:games' %}">
            <h2>Calendario partite da disputare</h2>
        </a>
    {% endif %}
    <ul>
    {% for l in games %}
        {% include "squadre/gameBody.html" with object=l %}
    {% endfor %}
    </ul>
{% else %}
    <h1>Benvenuto</h1>
    <a href="{% url 'login' %}">
        <button type="button">Login</button> 
    </a> 
    <a href="{% url 'register' %}">
        <button type="button">Registrati</button> 
    </a>
    {% include "slider.html" %}<br><br>
    <a href="{% url 'squadre:games' %}">
        <h2>Calendario partite da disputare</h2>
    </a>
    <ul>
    {% for l in games %}
        {% include "squadre/gameBody.html" with object=l %}
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

{% block js_files %}
{% load static %}
<script type="text/javascript" src="{% static 'scripts/scriptSlider.js'%}"></script>
{% endblock %}

code/templates/modObj.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<br>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
     
    {{ form.as_p }}
     
    <input type="submit" value="Conferma">
    <!-- TODO aggiungere pulsante annulla -->
</form>   

{% endblock %}

code/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Atletico rolo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bacheca:announcements' %}">Bacheca</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bacheca:posts' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'squadre:games' %}">Partite</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'squadre:teams' %}">Squadre</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Società
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'societa:members' %}">Organigramma</a></li>
            <li><a class="dropdown-item" href="{% url 'societa:sponsors' %}">Sponsor</a></li>
          </ul>
        </li>

      </ul>
      {% if user.is_authenticated %}
          <form class="d-flex" method="post" action="{% url 'logout' %}">{% csrf_token %}
            <button class="btn btn-danger" type="submit">Logout</button>
          </form>
      {% else %}
      <form class="d-flex" method="post" action="{% url 'login' %}">{% csrf_token %}
        <button class="btn btn-warning" type="submit">Login</button>
      </form>
      <form class="d-flex" method="post" action="{% url 'register' %}">{% csrf_token %}
        <button class="btn btn-success" type="submit">Registrati</button>
      </form>
      {% endif %}
    </div>
  </div>
</nav>

code/templates/slider.html
{% if images|length > 0 %}
    <div class="slider">
        {% for i in images %}
            {% if i != NULL and i != '' %}
                <div class="slider__page animate-slider">
                    <img src="{{i}}" alt="Immagine">
                </div>
            {% endif %}    
        {% endfor %}

        <div style="text-align:center">
            {% for n in range %}
                <span class="dot" onclick="currentSlide({{n}})"></span>
            {% endfor %}
        </div>
    </div>
{% endif %}

code/templates/success.html
{% extends 'base.html' %}

{% block title %} Successo {% endblock %}

{% block content %}

<h1> Operazione inoltrata correttamente </h1>
<br>
<a href="{% url back_url %}"><button type="button">Continua</button></a>

{% endblock %}

code/templates/user_create.html
{% extends 'base.html' %}

{% block title %} Registrazione {% endblock %}

{% block content %}

<h1>Registrazione</h1>

<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registrati">
    </form>
{% endblock %}