code/bacheca/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'bacheca'

urlpatterns = [  
    path('posts/', search_posts, name="posts"),
    path('annunci/', search_announcements, name="announcements"),

    path('post/<pk>/', DetailPostView.as_view(), name="post"),
    path('annuncio/<pk>/', DetailAnnouncementView.as_view(), name="announcement"),

    path('aggiungipost/', CreatePostView.as_view(), name="addpost"),
    path('aggiungiannuncio/', CreateAnnouncementView.as_view(), name="addannouncement"),

    path('authorizepost/', AuthorizePostView.as_view(), name="authorizepost"),
    path('approvepost/<pk>/', ApprovePostView.as_view(), name="approvepost"),

    path('commentapost/<int:id_post>/', CreateCommPostView.as_view(), name="addcommpost"),
    path('commentaannuncio/<int:id_ann>/', CreateCommAnnouncementView.as_view(), name="addcommannouncement"),

    path('eliminapost/<pk>/', DelPostView.as_view(), name="delpost"),
    path('eliminaannuncio/<pk>/', DelAnnouncementView.as_view(), name="delannouncement"),

    path('eliminacommentopost/<int:id_post>/<pk>/', DelCommPostView.as_view(), name="delcommpost"),
    path('eliminacommentoannuncio/<int:id_ann>/<pk>/', DelCommAnnouncementView.as_view(), name="delcommannouncement"),

    path('likepost/<int:id_post>/', like_post, name="likepost"),
    path('unlikepost/<int:id_post>/', unlike_post, name="unlikepost"),
]

code/societa/urls.py
from django.urls import path
from .views import *

app_name = 'societa'

urlpatterns = [  
    path('soci/', ListMemberView.as_view(), name="members"),
    path('sponsor/', ListSponsorView.as_view(), name="sponsors"),

    path('aggiungisocio/', CreateMemberView.as_view(), name="createmember"),
    path('aggiungisponsor/', CreateSponsorView.as_view(), name="createsponsor"),

    path('amministra/', adminClub, name="adminclub"),

    path('cancellasocio/<pk>/', DelMemberView.as_view(), name="delmember"),
    path('modificasocio/<pk>/', ModMemberView.as_view(), name="modmember"),

    path('cencellasponsor/<pk>/', DelSponsorView.as_view(), name="delsponsor"),
    path('modificasponsor/<pk>/', ModSponsorView.as_view(), name="modsponsor"),
]

code/sportnet/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r"^$|^/$|^home/$", home, name="home"),

    path('success/<str:back_url>', success_view, name="success"),

    path('register/', BasicUserCreateView.as_view(), name="register"),
    path('registersuper/',SuperUserCreateView.as_view(), name="registersuper"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('authorize/', AuthorizeUserView.as_view(), name="authorize"),
    path('approveuser/<pk>/', ApproveUserView.as_view(), name="approve"),

    path('squadre/', include('squadre.urls')),

    path('societa/', include('societa.urls')),

    path('bacheca/', include('bacheca.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

init_db()

code/societa/models.py
from django.db import models
from django.conf import settings
from sportnet.initcmds import club_logo_directory_path, club_member_directory_path


class Club(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    primary_color = models.CharField(max_length=7)
    secondary_color = models.CharField(max_length=7)
    logo = models.ImageField(
        upload_to=club_logo_directory_path,
        null=True,
        blank=True,
        default=None,
    )

    def __str__(self):
        return self.name


class Member(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    mail = models.EmailField()
    picture = models.ImageField(
        upload_to=club_member_directory_path,
        null=True,
        blank=True,
        default=None,
    )
    club = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
        related_name='management'
    )

    def __str__(self):
        return self.name + " " + self.surname


class Sponsor(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200) # TODO TextField
    website = models.URLField()
    logo = models.ImageField(
        upload_to="sponsors/",
        null=True,
        blank=True,
        default=None,
    )

    def __str__(self):
        return self.name


class Financing(models.Model):
    club = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
        related_name='is_finance'
    )
    sponsor = models.ForeignKey(
        Sponsor,
        on_delete=models.CASCADE,
        related_name='finance'
    )

    def __str__(self):
        return self.club.name + " is finance by " + self.sponsor.name


class Usership(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    club = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
        related_name='belongs_to'
    )

code/societa/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from .models import *
from .societacmds import *
from sportnet.initcmds import main_club


def adminClub(request):
    response = redirect("societa:members")
    get_querydict = request.GET.copy()
    try:
        item = get_querydict.popitem()
        int(item[1][0]) # se non causa un eccezzione allora è un intero
        if item[0] in accepted_path:
            response = redirect("societa:"+item[0], item[1][0])
    except KeyError:
        print("adminClub: WRONG PARAM")
    except ValueError:
        print("adminClub: NOT INT")
    except:
        print("adminClub: EXCEPTION UNKNOW")
    
    return response


class ListMemberView(ListView):
    model = Member
    template_name = "societa/members.html"
    title = "Organigramma"

    def get_queryset(self):
        # TODO filtro per club in base all'utente loggato 
        return self.model.objects.filter(club=main_club().pk)


class ListSponsorView(ListView):
    model = Sponsor
    template_name = "societa/sponsors.html"
    title = "Sponsor"

    def get_queryset(self):
        # TODO filtro per club in base all'utente loggato
        return self.model.objects.raw(
            """
            SELECT * FROM societa_sponsor
            INNER JOIN societa_financing ON societa_sponsor.id = societa_financing.sponsor_id
            WHERE societa_financing.club_id = 
            """
            + str(main_club().pk)
        )


class CreateMemberView(PermissionRequiredMixin, CreateView):
    model = Member
    template_name = "modObj.html"
    fields = member_mod_fields
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:members"})
    title = "Aggiungi socio"
    permission_required = "is_staff"

    def form_valid(self, form):
        # TODO metti il club in base all'utente loggato
        form.instance.club = main_club()
        return super().form_valid(form)


class CreateSponsorView(PermissionRequiredMixin, CreateView):
    model = Sponsor
    template_name = "modObj.html"
    fields = sponsor_mod_fields
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:sponsors"})
    title = "Aggiungi sponsor"
    permission_required = "is_staff"
    
    def form_valid(self, form):
        response = super().form_valid(form)
        if self.object is not None:
            bind = Financing()
            bind.club = main_club()
            bind.sponsor = self.object
            bind.save()
        return response


class DelMemberView(PermissionRequiredMixin, DeleteView):
    model = Member
    template_name = "delObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:members"})
    title = "Cancella socio"
    permission_required = "is_staff"


class DelSponsorView(PermissionRequiredMixin, DeleteView):
    model = Sponsor
    template_name = "delObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:sponsors"})
    title = "Cancella sponsor"
    permission_required = "is_staff"


class ModMemberView(PermissionRequiredMixin, UpdateView):
    model = Member
    template_name = "modObj.html"
    fields = member_mod_fields
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:members"})
    title = "Modifica socio"
    permission_required = "is_staff"


class ModSponsorView(PermissionRequiredMixin, UpdateView):
    model = Sponsor
    template_name = "modObj.html"
    fields = sponsor_mod_fields
    success_url = reverse_lazy("success", kwargs={"back_url": "societa:sponsors"})
    title = "Modifica sponsor"
    permission_required = "is_staff"

code/societa/templates/societa/members.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<div>
{% for l in object_list|dictsort:"surname" %}
<ul>
    <!-- TODO suddividere i soci in base al ruolo-->
    {% if l.picture != NULL and l.picture != '' %}
    <img src="{{l.picture.url}}" alt="foto" height="100" width="100">
    {% endif %}
    <p>Ruolo: {{l.role}}</p>
    <p>{{ l.name }} {{ l.surname }}</p>
</ul>
{% endfor %}
</div>

{% if user.is_staff %}
  <div>
    <a href="{% url 'societa:createmember' %}"> <input type="button" value="Aggiungi un socio all'organigramma"></a>
    
    <br><br>
    
    <form action="{% url 'societa:adminclub' %}">
        <label for="MemberDel">Scegli un socio da ELIMINARE:</label>
        <select name="delmember" id="Memberdel">
          {% for l in object_list %}
    
          <option value="{{ l.pk }}">{{l.surname}} {{l.name}}</option>
    
          {% endfor %}
        </select>
        <br>
        <input type="submit" value="Elimina">
    </form>
    
    <br><br>
    <form action="{% url 'societa:adminclub' %}">
      <label for="MemberMod">Scegli un socio da MODIFICARE:</label>
      <select name="modmember" id="Membermod">
        {% for l in object_list %}
    
        <option value="{{ l.pk }}">{{l.surname}} {{l.name}}</option>
    
        {% endfor %}
      </select>
      <br>
      <input type="submit" value="Modifica">
    </form>
  </div>
{% endif %}
{% endblock content %}

code/societa/templates/societa/sponsors.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<div>
{% for l in object_list|dictsort:"name" %}
<div class="card" style="width: 18rem;">
  {% if l.logo != NULL and l.logo != '' %}
  <img src="{{l.logo.url}}" alt="logo" class="card-img-top">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ l.name }}</h5>
    <p class="card-text">{{ l.description }}</p>
    <a href="{{ l.website }}" class="btn btn-primary">Sito wbe</a>
  </div>
</div>
<br>
{% endfor %}
</div>

{% if user.is_staff %}
  <div>
  <a href="{% url 'societa:createsponsor' %}"> <input type="button" value="Aggiungi uno sponsor"></a>

  <br><br>

  <form action="{% url 'societa:adminclub' %}">
      <label for="SponsorDel">Scegli uno sponsor da ELIMINARE:</label>
      <select name="delsponsor" id="Sponsordel">
        {% for l in object_list %}

        <option value="{{ l.pk }}">{{l.name}}</option>

        {% endfor %}
      </select>
      <br>
      <input type="submit" value="Elimina">
  </form>

  <br><br>
  <form action="{% url 'societa:adminclub' %}">
    <label for="SponsorMod">Scegli un socio da MODIFICARE:</label>
    <select name="modsponsor" id="Sponsormod">
      {% for l in object_list %}

      <option value="{{ l.pk }}">{{l.name}}</option>

      {% endfor %}
    </select>
    <br>
    <input type="submit" value="Modifica">
  </form>
  </div>
{% endif %}
{% endblock content %}