code/bacheca/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'bacheca'

urlpatterns = [  
    path('posts/', search_posts, name="posts"),
    path('annunci/', search_announcements, name="announcements"),

    path('post/<pk>/', DetailPostView.as_view(), name="post"),
    path('annuncio/<pk>/', DetailAnnouncementView.as_view(), name="announcement"),

    path('aggiungipost/', CreatePostView.as_view(), name="addpost"),
    path('aggiungiannuncio/', CreateAnnouncementView.as_view(), name="addannouncement"),

    path('authorizepost/', AuthorizePostView.as_view(), name="authorizepost"),
    path('approvepost/<pk>/', ApprovePostView.as_view(), name="approvepost"),

    path('commentapost/<int:id_post>/', CreateCommPostView.as_view(), name="addcommpost"),
    path('commentaannuncio/<int:id_ann>/', CreateCommAnnouncementView.as_view(), name="addcommannouncement"),

    path('eliminapost/<pk>/', DelPostView.as_view(), name="delpost"),
    path('eliminaannuncio/<pk>/', DelAnnouncementView.as_view(), name="delannouncement"),

    path('eliminacommentopost/<int:id_post>/<pk>/', DelCommPostView.as_view(), name="delcommpost"),
    path('eliminacommentoannuncio/<int:id_ann>/<pk>/', DelCommAnnouncementView.as_view(), name="delcommannouncement"),

    path('likepost/<int:id_post>/', like_post, name="likepost"),
    path('unlikepost/<int:id_post>/', unlike_post, name="unlikepost"),
]

code/sportnet/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r"^$|^/$|^home/$", home, name="home"),

    path('success/<str:back_url>', success_view, name="success"),

    path('register/', BasicUserCreateView.as_view(), name="register"),
    path('registersuper/',SuperUserCreateView.as_view(), name="registersuper"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('authorize/', AuthorizeUserView.as_view(), name="authorize"),
    path('approveuser/<pk>/', ApproveUserView.as_view(), name="approve"),

    path('squadre/', include('squadre.urls')),

    path('societa/', include('societa.urls')),

    path('bacheca/', include('bacheca.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

init_db()

code/squadre/urls.py
from django.urls import path
from .views import *


app_name = 'squadre'


urlpatterns = [
    path('', ListTeamsView.as_view(), name="teams"),
    path('rosa/<pk>/', DetailTeamView.as_view(), name="team"),

    path('giocatore/<pk>/', DetailPlayerView.as_view(), name="player"),

    path('partite/', search_games, name="games"),
    path('aggiungipartita/', CreateGameView.as_view(), name="creategame"),
    path('risultatopartita/<pk>/', ResGameView.as_view(), name="resgame"),
    path('convocazionepartita/<pk>/', ConGameView.as_view(), name="congame"),
    path('cancellapartita/<pk>/', DelGameView.as_view(), name="delgame"),
    
    path('squadrapreferita/<pk>/', SetPrefTeamView.as_view(), name="prefteam"),

    path('stampaconvocati/<int:id_game>/', print_convocation, name="printcov"),
    
]

code/squadre/models.py
from django.db import models
from societa.models import Club
from sportnet.initcmds import team_directory_path
from django.core.exceptions import ValidationError
from django.conf import settings
from django.utils import timezone


class Team(models.Model):
    name = models.CharField(max_length=50, default="")
    year = models.CharField(max_length=4)
    mister = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default=None
    )
    club = models.ForeignKey(
        Club,
        null=True,
        blank=True,
        default=None,
        on_delete=models.CASCADE,
        related_name='train',
    )

    def __str__(self):
        return self.name + "(" +str(self.year) + ")"


class Player(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birthday = models.DateField()
    picture = models.FileField(
        upload_to=team_directory_path,
        null=True,
        blank=True,
        default=None,
    )
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        related_name='play'
    )

    def __str__(self):
        return self.first_name + " " + self.last_name

class Game(models.Model):
    date = models.DateTimeField()
    place = models.CharField(max_length=200)
    points_team1 = models.IntegerField(default=0)
    points_team2 = models.IntegerField(default=0)
    team1 = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        related_name='participate_h',
    )
    team2 = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        related_name='participate_a',
    )

    players = models.ManyToManyField(
        Player,
        blank=True,
        default=None,
        db_table = 'convocation',
        related_name='convocated'
    )

    def clean(self):
        if self.team1.id == self.team2.id:
            raise ValidationError("Team cannot play against itself")
        if self.id != None:
            for player in self.players.all():
                if player.team.pk != self.team1.pk and player.team.pk != self.team2.pk:
                    self.players.remove(player)
                    raise ValidationError("Player must play for one of the 2 teams")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def winner(self):
        winner_team = "Pareggio"
        if self.points_team1 > self.points_team2:
            winner_team = self.team1
        elif self.points_team2 > self.points_team1:
            winner_team = self.team2
        return str(winner_team)

    def __str__(self):
        return str(self.team1) + " VS " +str(self.team2)


class PrefTeam(models.Model):
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        default=None,
        on_delete=models.CASCADE,
        related_name='is_preferred'
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='follow',
        primary_key=True
    )

code/squadre/forms.py
from django import forms
from .models import *

class SearchGamesForm(forms.Form):
    search_date = forms.DateField(
        label="Cerca una partita in data:",
        required=False
    )
    search_place = forms.CharField(
        label="Cerca una partita nel luogo:",
        max_length=200,
        required=False
    )
    search_team = forms.ModelChoiceField(
        queryset=Team.objects.all(),
        required=False,
        label="Cerca una squadra"
    )
    search_team_result = forms.ChoiceField(
        label="Che risultato ha ottenuto la squadra?",
        required=False,
        choices=[
            ("Qualsiasi","Qualsiasi risultato"),
            ("Vittoria","Hanno vinto"),
            ("Sconfitta","Hanno perso"),
            ("Pareggio","Hanno pareggiato")
        ],
        widget=forms.RadioSelect,
    )
    search_player = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        required=False,
        label="Cerca un giocatore"
    )
    order_date = forms.ChoiceField(
        label="Ordina per data",
        required=False,
        choices=[
            ("-date","Dalla più recente(Default)"),
            ("date","Dalla meno recente")
        ],
        widget=forms.RadioSelect,
    )

code/squadre/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from braces.views import GroupRequiredMixin, UserPassesTestMixin
from sportnet.initcmds import i_page_range
from .squadrecmds import QueryGameForm
from .models import *
from .forms import *


game_page_len = 5


def print_convocation(request, id_game):
    ctx = {}
    try:
        id_g = int(id_game)
        game = Game.objects.get(id=id_g)
        players = game.players.all()
        ctx["object_list"] = players
        ctx["game"] = game
    except:
        ctx["object_list"] = []
        ctx["game"] = ""
    return render(request, template_name="squadre/convocationDoc.html", context=ctx)


class ListTeamsView(ListView):
    model = Team
    template_name = "squadre/teams.html"
    title = "Squadre"


class DetailTeamView(DetailView):
    model = Team
    template_name = "squadre/team.html"


class DetailPlayerView(DetailView):
    model = Player
    template_name = "squadre/player.html"


def search_games(request):
    ctx = {}
    q = Game.objects.all()
    form = SearchGamesForm()
    page_num = 1
    order = "-date"

    if request.method == "POST":
        form = SearchGamesForm(request.POST)
        if form.is_valid():
            qpg = QueryGameForm(q, form)
            q = qpg.query_search()
            order = qpa.query_order()

            try: page_num = int(request.POST["page"])
            except: page_num = 1

    i_page_start, i_page_end, tot_page = i_page_range(len(q), game_page_len, page_num)
    q = q.order_by(order)

    ctx["object_list"] = q[i_page_start:i_page_end]
    ctx["page"] = page_num
    ctx["range"] = range(1,tot_page+1)
    ctx["form"] = form
    return render(request, template_name="squadre/games.html", context=ctx)

class ListGamesView(ListView):
    model = Game
    template_name = "squadre/games.html"
    title = "Partite"


class CreateGameView(GroupRequiredMixin,CreateView):
    model = Game
    template_name = "modObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "squadre:games"})
    fields = ["date","place","team1","points_team1", "team2","points_team2"]
    group_required = ["Super"]
    title = "Aggiungi partita"

class ResGameView(GroupRequiredMixin,UpdateView):
    model = Game
    template_name = "modObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "squadre:games"})
    fields = ["points_team1", "points_team2"]
    group_required = ["Super"]
    title = "Risultato partita"


class ConGameView(GroupRequiredMixin,UpdateView):
    model = Game
    template_name = "modObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "squadre:games"})
    fields = ["players"]
    group_required = ["Super"]
    title = "Convicazione partita"


class DelGameView(GroupRequiredMixin,DeleteView):
    model = Game
    template_name = "delObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "squadre:games"})
    group_required = ["Super"]
    title = "Elimina partita"


class SetPrefTeamView(UserPassesTestMixin, UpdateView):
    model = PrefTeam
    template_name = "modObj.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "home"})
    fields = ["team"]
    title = "Scegli squadra preferita"
    
    def test_func(self, user): 
        return (user.pk == self.get_object().user.pk or user.is_staff)

code/squadre/templates/squadre/convocationDoc.html
{% extends 'base.html' %}

{% block title %} Convocazione {% endblock %}

{% block content %}

<h1> Convocazione {{game}} </h1>
<ul>
    {% for l in object_list|dictsort:"last_name" %}

    <li>{{l.last_name}} {{l.first_name}} nato il {{l.birthday}}</li>

    {% endfor %}
</ul>

{% endblock %}

code/squadre/templates/squadre/gameBody.html
<li>
<p>{{ object }}</p>
<p>Risultato: {{object.points_team1}}:{{object.points_team2}}</p>
<p>Vincitore: {{object.winner}}</p>
<p>Luogo: {{object.place}}</p>
<p>Data: {{object.date}}</p>
{% if "Super" in user.groups.all.0.name or user.is_staff %}
    <a href="{% url 'squadre:resgame' object.pk %}"><button type="button">Modifica risultato</button></a>
    <a href="{% url 'squadre:congame' object.pk %}"><button type="button">Convoca</button></a>
    <br>
{% endif %}
</li>

code/squadre/templates/squadre/games.html
{% extends 'base.html' %}

{% block title %} Partite {% endblock %}

{% block content %}

<h1> Lista partite </h1>

<form action="{% url 'squadre:games' %}" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Esegui"><br><br>
    <p>Pagina:</p>
    {% for i in range %}
        {% if i == page %}
            {{i}} 
        {% else %}
            <input type="submit" name="page" value="{{i}}">
        {% endif %}
    {% endfor %}
    <br>
</form>
<br>
<ul>
{% for l in object_list %}
    {% include "squadre/gameBody.html" with object=l %}
{% endfor %}
</ul>

{% endblock content %}

code/squadre/templates/squadre/player.html
{% extends 'base.html' %}

{% block title %} Giocatore {{object.team.year}} {% endblock %}

{% block content %}

<h1> Dettagli Giocatore {{object.first_name}} {{object.last_name}}</h1>

<br>
<p>Nato il {{object.birthday}}</p>
<br>
<p>Attulmente gioca per <a href="{% url 'squadre:team' object.team.pk %}">{{object.team}}</a></p>
<br>
{% if object.picture != NULL and object.picture != '' %}
    <img src="{{object.picture.url}}" alt="immagine giocatore" height="150" width="100">
{% endif %}
{% endblock %}

code/squadre/templates/squadre/team.html
{% extends 'base.html' %}

{% block title %} Squadra {{object.year}} {% endblock %}

{% block content %}

<h1> {{object}} </h1>

<br>
{% if object.play.all.count < 1 %}
    <p>La squandra non ha giocatori</p>
{% else %}
    <ul>
    {% for s in object.play.all|dictsort:"last_name" %}
        <li>
            <a href="{% url 'squadre:player' s.pk %}">
                <img src="{{s.picture.url}}" alt="immagine giocatore" height="150" width="100">
            </a>
            <br>
            <a href="{% url 'squadre:player' s.pk %}">
                <p>{{s.first_name}} {{s.last_name}}</p>
            </a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

code/squadre/templates/squadre/teams.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>
<div>
    {% for l in object_list|dictsort:"year"|dictsort:"name" %}
    <ul>
        <li><a href="{% url 'squadre:team' l.pk %}">{{l}}</a></li>
    </ul>
    {% endfor %}
    </div>

{% endblock %}