code/bacheca/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'bacheca'

urlpatterns = [  
    path('posts/', search_posts, name="posts"),
    path('annunci/', search_announcements, name="announcements"),

    path('post/<pk>/', DetailPostView.as_view(), name="post"),
    path('annuncio/<pk>/', DetailAnnouncementView.as_view(), name="announcement"),

    path('aggiungipost/', CreatePostView.as_view(), name="addpost"),
    path('aggiungiannuncio/', CreateAnnouncementView.as_view(), name="addannouncement"),

    path('authorizepost/', AuthorizePostView.as_view(), name="authorizepost"),
    path('approvepost/<pk>/', ApprovePostView.as_view(), name="approvepost"),

    path('commentapost/<int:id_post>/', CreateCommPostView.as_view(), name="addcommpost"),
    path('commentaannuncio/<int:id_ann>/', CreateCommAnnouncementView.as_view(), name="addcommannouncement"),

    path('eliminapost/<pk>/', DelPostView.as_view(), name="delpost"),
    path('eliminaannuncio/<pk>/', DelAnnouncementView.as_view(), name="delannouncement"),

    path('eliminacommentopost/<int:id_post>/<pk>/', DelCommPostView.as_view(), name="delcommpost"),
    path('eliminacommentoannuncio/<int:id_ann>/<pk>/', DelCommAnnouncementView.as_view(), name="delcommannouncement"),

    path('likepost/<int:id_post>/', like_post, name="likepost"),
    path('unlikepost/<int:id_post>/', unlike_post, name="unlikepost"),
]

code/sportnet/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r"^$|^/$|^home/$", home, name="home"),

    path('success/<str:back_url>', success_view, name="success"),

    path('register/', BasicUserCreateView.as_view(), name="register"),
    path('registersuper/',SuperUserCreateView.as_view(), name="registersuper"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('authorize/', AuthorizeUserView.as_view(), name="authorize"),
    path('approveuser/<pk>/', ApproveUserView.as_view(), name="approve"),

    path('squadre/', include('squadre.urls')),

    path('societa/', include('societa.urls')),

    path('bacheca/', include('bacheca.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

init_db()

code/bacheca/models.py
from django.db import models
from sportnet.initcmds import post_directory_path
from django.conf import settings
from squadre.models import Team, Player, Game
from django.utils import timezone


class Comment(models.Model):
    desc = models.TextField(max_length=500)
    date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    class Meta:
        abstract = True


class Post(Comment):
    approved = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to=post_directory_path,
        null=True,
        blank=True,
        default=None
    )
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        default=None,
        on_delete=models.PROTECT,
        related_name='reference'
    )
    game = models.ForeignKey(
        Game,
        null=True,
        blank=True,
        default=None,
        on_delete=models.PROTECT,
        related_name='reference'
    )
    players = models.ManyToManyField(
        Player,
        blank=True,
        default=None,
        related_name='tagged'
    )
    def __str__(self):
        return str(self.user.username) + " post " + str(self.pk)


class Announcement(Comment):
    title = models.CharField(max_length=50)
    teams = models.ManyToManyField(
        Team,
        blank=True,
        default=None,
        related_name='ann_reference',
    )
    def __str__(self):
        return self.title

class PostComment(Comment):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )


class AnnouncementComment(Comment):
    announcement = models.ForeignKey(
        Announcement,
        on_delete=models.CASCADE,
        related_name='comments'
    )


class LikeImage(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='is_liked'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='like_a'
    )
    def __str__(self):
        return self.user.username + " like " + str(self.post)

code/bacheca/forms.py
from django import forms
from django.conf import settings
from .models import *
from django.contrib.auth.models import User


class SearchCommentsForm(forms.Form):
    search_date = forms.DateField(
        label="Cerca post pubblicato in data:",
        required=False
    )
    search_user = forms.ModelChoiceField(
        queryset= User.objects.all(),
        required=False,
        label="Cerca per utente"
    )
    search_desc = forms.CharField(
        label="Cerca parole nella descrizione",
        max_length=200,
        required=False
    )
    search_team = forms.ModelChoiceField(
        queryset=Team.objects.all(),
        required=False,
        label="Cerca una squadra"
    )
    order_date = forms.ChoiceField(
        label="Ordina per data",
        required=False,
        choices=[
            ("-date","Dalla pubblicazione più recente(Default)"),
            ("date","Dalla pubblicazione meno recente")
        ],
        widget=forms.RadioSelect,
    )


class SearchPostsForm(SearchCommentsForm):
    search_game = forms.ModelChoiceField(
        queryset=Game.objects.all(),
        required=False,
        label="Cerca una partita"
    )
    search_player = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        required=False,
        label="Cerca un giocatore"
    )


class SearchAnnouncemenForm(SearchCommentsForm):
    search_title = forms.CharField(
        label="Cerca parole nella descrizione",
        max_length=50,
        required=False
    )

code/bacheca/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import PermissionRequiredMixin
from braces.views import GroupRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from sportnet.initcmds import i_page_range
from .models import *
from .forms import *
from .bachecacmds import QueryPostsForm, QueryAnnouncementsForm


post_page_len = 5
ann_page_len = 5

class AuthorizePostView(ListView):
    model = Post
    template_name = "bacheca/authPosts.html"
    title = "Autorizza post"

    def get_queryset(self):
        print(Post.objects.filter(approved=False))
        return Post.objects.filter(approved=False)


class ApprovePostView(PermissionRequiredMixin, UpdateView):
    model = Post
    template_name = "bacheca/apprPost.html"
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:authorizepost"})
    title = "Approva post"
    fields = []
    permission_required = "is_staff"

    def form_valid(self, form):
        self.object.approved = True
        return super().form_valid(form)


def search_posts(request):
    ctx = {}
    q = Post.objects.all().filter(approved=True)
    form = SearchPostsForm()
    page_num = 1
    order = "-date"

    if request.method == "POST":
        form = SearchPostsForm(request.POST)
        if form.is_valid():
            qpf = QueryPostsForm(q, form)
            q = qpf.query_search()
            order = qpf.query_order()

            try: page_num = int(request.POST["page"])
            except: page_num = 1

    i_page_start, i_page_end, tot_page = i_page_range(len(q), post_page_len, page_num)
    q = q.order_by(order)

    ctx["object_list"] = q[i_page_start:i_page_end]
    ctx["page"] = page_num
    ctx["range"] = range(1,tot_page+1)
    ctx["form"] = form
    return render(request, template_name="bacheca/posts.html", context=ctx)


def search_announcements(request):
    ctx = {}
    q = Announcement.objects.all()
    form = SearchAnnouncemenForm()
    page_num = 1
    order = "-date"

    if request.method == "POST":
        form = SearchAnnouncemenForm(request.POST)
        if form.is_valid():
            qpa = QueryAnnouncementsForm(q, form)
            q = qpa.query_search()
            order = qpa.query_order()

            try: page_num = int(request.POST["page"])
            except: page_num = 1

    i_page_start, i_page_end, tot_page = i_page_range(len(q), ann_page_len, page_num)
    q = q.order_by(order)

    ctx["object_list"] = q[i_page_start:i_page_end]
    ctx["page"] = page_num
    ctx["range"] = range(1,tot_page+1)
    ctx["form"] = form
    return render(request, template_name="bacheca/anns.html", context=ctx)


def like_post(request, id_post):
    response = False
    if request.user.is_authenticated:
        try:
            id_p = int(id_post)
            likes = LikeImage.objects.filter(user__pk=request.user.pk)
            likes = likes.filter(post__pk=id_p)
            if len(likes) == 0:
                like = LikeImage()
                like.user = request.user
                like.post = Post.objects.get(pk=id_p)
                like.save()
                response = True
        except: response = False
    return HttpResponse(response)


def unlike_post(request, id_post):
    response = False
    if request.user.is_authenticated:
        try:
            id_p = int(id_post)
            likes = LikeImage.objects.filter(user__pk=request.user.pk)
            likes = likes.filter(post__pk=id_p)
            for like in likes:
                like.delete()
                response = True
            likes = LikeImage.objects.filter(user__pk=request.user.pk)
            likes = likes.filter(post__pk=id_p)
        except: response = False
    return HttpResponse(response)


class DetailPostView(DetailView):
    model = Post
    template_name = "bacheca/post.html"


class DetailAnnouncementView(DetailView):
    model = Announcement
    template_name = "bacheca/ann.html"


class CreateCommentView(GroupRequiredMixin, CreateView):
    template_name = "modObj.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CreatePostView(CreateCommentView):
    model = Post
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:posts"})
    fields = ["desc","image","team","game","players"]
    group_required = ["Approved"]
    title = "Pubblica post"
    def form_valid(self, form):
        if self.request.user.is_staff:
            form.instance.approved = True
        return super().form_valid(form)


class CreateAnnouncementView(CreateCommentView):
    model = Announcement
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:announcements"})
    fields = ["title","desc","teams"]
    group_required = ["Super"]
    title = "Pubblica annuncio"


class CreateCommPostView(CreateCommentView):
    model = PostComment
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:posts"})
    fields = ["desc"]
    group_required = ["Approved"]
    title = "Commenta post"

    def form_valid(self, form):
        p = Post.objects.get(pk=self.kwargs["id_post"])
        form.instance.post = p
        return super().form_valid(form)


class CreateCommAnnouncementView(CreateCommentView):
    model = AnnouncementComment
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:announcements"})
    fields = ["desc"]
    group_required = ["Approved"]
    title = "Commenta annuncio"

    def form_valid(self, form):
        a = Announcement.objects.get(pk=self.kwargs["id_ann"])
        form.instance.announcement = a
        return super().form_valid(form)


class DelCommentView(UserPassesTestMixin, DeleteView):
    template_name = "delObj.html"
    def test_func(self, user): 
        return (user.pk == self.get_object().user.pk or user.is_staff)

class DelPostView(DelCommentView):
    model = Post
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:posts"})
    title = "Cancella post"


class DelAnnouncementView(DelCommentView):
    model = Announcement
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:announcements"})
    title = "Cancella annuncio"


class DelCommPostView(DelCommentView):
    model = PostComment
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:posts"})
    title = "Cancella commento post"


class DelCommAnnouncementView(DelCommentView):
    model = AnnouncementComment
    success_url = reverse_lazy("success", kwargs={"back_url": "bacheca:announcements"})
    title = "Cancella commento annuncio"

code/bacheca/templates/bacheca/ann.html
{% extends 'base.html' %}

{% block title %} Annuncio {% endblock %}

{% block content %}

{% include "bacheca/annBody.html" %}

{% if object.comments.all.count > 0 %}
    <p>Commenti: </p>
    <ul>
    {% for c in object.comments.all|dictsort:"date" %}
        <li>
            {% include "bacheca/commBody.html" with id_p_a=object.pk url_name='delcommannouncement' comm=c %}
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

code/bacheca/templates/bacheca/annBody.html
<h1><a href="{% url 'bacheca:announcement' object.pk %}">
    {{ object.title }}
</a></h1>
{% if user.pk == object.user.pk or user.is_staff %}
    <a href="{% url 'bacheca:delannouncement' object.pk %}">
        <button type="button">Elimina annuncio</button> 
    </a>
{% endif %}
<br> 
<p>Annuncio pubblicato da: {{object.user.username}}</p>

<p>Caricato in data {{object.date}}</p>
<p>Descrizione: {{object.desc}}</p>

{% if object.teams.all.count > 0 %}
    <h3>Squadre taggate</h3>
    <ul>
    {% for t in object.teams.all|dictsort:"year"|dictsort:"name" %}
        <li>
            <p>{{t}}</p>
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% if user.is_authenticated %}
    <a href="{% url 'bacheca:addcommannouncement' object.pk %}">
        <button type="button">Commenta</button> 
    </a>
{% endif %}
  

code/bacheca/templates/bacheca/anns.html
{% extends 'base.html' %}

{% block title %} Annunci {% endblock %}

{% block content %}

<h1> Lista annunci </h1>
{% if "Super" in user.groups.all.0.name or user.is_staff %}
    <a href="{% url 'bacheca:addannouncement'%}" ><button class="btn btn-success" type="button">Crea annuncio</button> </a>
{% endif %}

<form action="{% url 'bacheca:announcements' %}" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Esegui"><br><br>
    <p>Pagina:</p>
    {% for i in range %}
        {% if i == page %}
            {{i}} 
        {% else %}
            <input type="submit" name="page" value="{{i}}">
        {% endif %}
    {% endfor %}
    <br>
</form>
<br>
<ul>
{% for l in object_list %}
    <li>
    {% include "bacheca/annBody.html" with object=l %}
    </li>
    {% if l.comments.all.count > 0 %}
        <h3>Commenti</h3>
        <ul>
        {% for c in l.comments.all|dictsort:"date"|slice:2 %}
            <li>
                {% include "bacheca/commBody.html" with id_p_a=l.pk url_name='delcommannouncement' comm=c %}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endfor %}
</ul>

{% endblock content %}

code/bacheca/templates/bacheca/apprPost.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<h2>Sicuro di voler approvare il post?</h2>
{% include "bacheca/postBody.html" %}

<form method="post">{% csrf_token %}
     
    <input type="submit" value="Conferma">
    <!-- TODO aggiungere pulsante annulla -->
</form>


{% endblock content %}

code/bacheca/templates/bacheca/authPosts.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% block content %}

<h1> {{view.title}} </h1>

<div>
    <table>
        <tr>
            <th>Utente</th>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Descrizione</th>
            <th>Immagine</th>
            <th>Autorizza</th>
        </tr>

        {% for l in object_list|dictsort:"user.username" %}
        <tr>
            <th><p>{{l.user.username}}</p></th>
            <th><p>{{l.user.first_name}}</p></th>
            <th><p>{{l.user.last_name}}</p></th>
            <th><p>{{l.desc}}</p></th>
            <th>
                {% if l.image != NULL and l.image != '' %}
                    <img src="{{l.image.url}}" alt="immagine post">
                {% endif %}
            </th>
            <th><a href="{% url 'bacheca:approvepost' l.pk %}"><button type="button">Autorizza</button></a></th>
        </tr>

        {% endfor %}
    </table>

</div>

{% endblock content %}

code/bacheca/templates/bacheca/commBody.html
{% if user.pk == comm.user.pk or user.is_staff %}
    <a href="{% url 'bacheca:'|add:url_name id_p_a comm.pk %}">
        <button type="button">Elimina commento</button> 
    </a>
    <br>
{% endif %}
<p>Commento di {{comm.user.username}} in data {{comm.date}}</p>
<p>Commento: {{comm.desc}}</p>

code/bacheca/templates/bacheca/post.html
{% extends 'base.html' %}

{% block title %} Post di {{object.user.username}} {% endblock %}

{% block content %}
{% include "bacheca/postBody.html" %}
{% if object.comments.all.count > 0 %}
<h3>Commenti</h3>
    <ul>
    {% for c in object.comments.all|dictsort:"date" %}
        <li>
            {% include "bacheca/commBody.html" with id_p_a=object.pk url_name='delcommpost' comm=c %}
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}
{% block js_files %}
{% load static %}
    <script type="text/javascript" src="{% static 'scripts/scriptLikeImage.js'%}"></script>
{% endblock js_files %}

code/bacheca/templates/bacheca/postBody.html
<div class="card" style="width: 18rem;">
    {% if object.image != NULL and object.image != '' %}
        <img src="{{object.image.url}}" class="card-img-top" alt="immagine post">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{% url 'bacheca:post' object.pk %}">
                Post di {{object.user.username}}
            </a>
        </h5>
        <p class="card-text">{{object.desc}}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Caricato in data {{object.date}}</li>
        {% if object.team != None %}
            <li class="list-group-item">Squadra taggata: {{object.team}}</li>
        {% endif %}
        {% if object.game != None %}
            <li class="list-group-item">Partita taggata: {{object.game}}</li>
        {% endif %}
        {% if object.players.all.count > 0 %}
            <li class="list-group-item">
                <h6>Giocatori taggati</h6>
                <ul>
                {% for p in object.players.all|dictsort:"last_name" %}
                    <li>
                        <p>{{p.first_name}} {{p.last_name}}</p>
                    </li>
                {% endfor %}
                </ul>
            </li>
        {% endif %}
    </ul>
    <div class="card-body">
        {% if user.pk == object.user.pk or user.is_staff %}
            <button href="{% url 'bacheca:delpost' object.pk %}" class="btn btn-danger" type="button">Elimina post</button> 
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'bacheca:addcommpost' object.pk %}">
                <button type="button">Commenta</button> 
            </a>
            <button class="btn btn-secondary btn-sm" type="button" onclick="sendLike({{object.pk}})"><3</button> 
            <button class="btn btn-secondary btn-sm" type="button" onclick="sendUnLike({{object.pk}})"><\3</button> 
        {% endif %}
    </div>
</div>

code/bacheca/templates/bacheca/posts.html
{% extends 'base.html' %}

{% block title %} Post {% endblock %}

{% block content %}

<h1> Lista post </h1>
{% if user.is_authenticated %}
    <a href="{% url 'bacheca:addpost'%}"><button class="btn btn-success" type="button">Crea post</button> </a>
{% endif %}

<form action="{% url 'bacheca:posts' %}" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Esegui"><br><br>
    <p>Pagina:</p>
    {% for i in range %}
        {% if i == page %}
            {{i}} 
        {% else %}
            <input type="submit" name="page" value="{{i}}">
        {% endif %}
    {% endfor %}
    <br>
</form>
<br>
<ul>
{% for l in object_list %}
    <li>
    {% include "bacheca/postBody.html" with object=l %}
    </li>
    {% if l.comments.all.count > 0 %}
        <h3>Commenti</h3>
        <ul>
        {% for c in l.comments.all|dictsort:"date"|slice:2 %}
            <li>
                {% include "bacheca/commBody.html" with id_p_a=l.pk url_name='delcommpost' comm=c %}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endfor %}
</ul>

{% endblock content %}

{% block js_files %}
{% load static %}
    <script type="text/javascript" src="{% static 'scripts/scriptLikeImage.js'%}"></script>
{% endblock js_files %}